// src/components/trackcard.vue
<template>
	<div class="card is-horizontal">
		<div class="card-image is-horizontal">
			<figure class="image is-160x160 is-horizontal">
				<img :key="this.boardJacket" v-bind:src="this.boardJacket" alt="Placeholder image" style="width:160px;height:160px;"/>
			</figure>
		</div>
		
		<div class="card-content is-horizontal">
	
			<div class="media-content">
				<p class="title is-4">{{title}}</p>
				<p class="subtitle is-6">{{artists}}</p>
			</div>
	
			<div class="content is-horizontal">
	
				<div> &nbsp; </div>
				<div> &nbsp; </div>
				<div> &nbsp; </div>
				<div> &nbsp; </div>
				
				<div class="container columns">
					<div v-for="board in boardList" class="column field has-addons">
						<boardbutton v-bind:rating="board.difficulty_rating" v-bind:diff="board.difficulty_name" v-bind:track_id="board.track_id" v-bind:board_id="board.id"/>
					</div>
				</div>
			</div>
		</div>
	</div>
</template>

<script>
import boardbutton from "@/components/boardbutton.vue";
import api from "@/api";
import axios from 'axios';

export default {
    name: "trackcard",
	props: ["id", "title", "artists"],
	components: {
		boardbutton
    },
	data() {
		return {
			boardList: [],
			boardJacket: "https://via.placeholder.com/160x160.webp"
		};
	},
	async created() {
		let boards = await api.board.getFromTrack(this.id);
		this.boardList = await boards.sort(function (propName) {
			return function(a, b) {
				if (a[propName] > b[propName]) {
					return 1;
				} else if (a[propName] < b[propName]) {
					return -1;
				}
				return 0;
			}
		}("difficulty_rating"));
		this.boardJacket = this.boardList[0].jacket;
	}
}
</script>

// src/components/track-card.jsx
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import styled, { css } from 'styled-components';
import { Button } from 'react-bulma-components';
import 'react-bulma-components/dist/react-bulma-components.min.css';
import 'bulmaswatch/cyborg/bulmaswatch.min.css';

function TrackCard({id, title, artists}) {
    useEffect(() => {
        fetchBoardsFromTrack();
    }, []);

    const [boards, setBoards] = useState([]);

    const fetchBoardsFromTrack = async () => {
        const req = await axios.get(`http://localhost:1000/api/v0/board/track/${id}`);

        const boards = await req.data;
        setBoards(boards);
    }

    const NoviceButton = styled(Button)`
        background-color: #6515ea;
    `

    const MaximumButton = styled(Button)`
        background-color: #FFFFFF;
        color: #000000;
    `

    const GravityButton = styled(Button)`
        background-color: #ff8000;
    `

    const HeavenlyButton = styled(Button)`
        background-color: #ceffff;
        color: #000000;
    `

    const VividButton = styled(Button)`
        background-color: #ffbae7;
    `

    return (
        <div
        className="card is-horizontal"
        >
            <div
            className="card-image is-horizontal"
            >
                <figure
                className="image is-320x180 is-horizontal"
                >
                    <img
                    src="https://via.placeholder.com/320x180.webp"
                    alt="Placeholder image"
                    />
                </figure>
            </div>
            <div
            className="card-content is-horizontal"
            >
                <div
                className="media-content"
                >
                    <p
                    className="title is-4"
                    >
                    {title}
                    </p>
                    <p
                    className="subtitle is-6"
                    >
                    {artists}
                    </p>
                </div>

                <div
                className="content is-horizontal"
                >
                <div> &nbsp; </div>
                <div> &nbsp; </div>
                <div> &nbsp; </div>
                <div> &nbsp; </div>
                <div className="field has-addons">
                {
                    boards.map(board => {
                        if (board.difficulty_rating > 20) {
                            board.difficulty_rating = "20+"
                        }

                        switch (board.difficulty_name) {
                            case 0: // novice
                                return <p
                                className="control"
                                >
                                    <Button
                                    renderAs={NoviceButton}
                                    >
                                        {board.difficulty_rating}
                                    </Button>
                                </p>
                            break;
                            case 1: // advanced
                                return <p
                                className="control"
                                >
                                    <Button
                                    className="is-warning"
                                    >
                                        {board.difficulty_rating}
                                    </Button>
                                </p>
                            break;
                            case 2: // exhaust
                                return <p
                                className="control"
                                >
                                    <Button
                                    className="is-danger"
                                    >
                                    {board.difficulty_rating}
                                    </Button>
                                </p>
                            break;
                            case 3: // maximum
                                return <p
                                className="control"
                                >
                                    <Button
                                    renderAs={MaximumButton}>
                                        {board.difficulty_rating}
                                    </Button>
                                </p>
                            break;
                            case 4: // infinite (green for now)
                                return <p
                                className="control"
                                >
                                    <Button
                                    className="is-success"
                                    >
                                        {board.difficulty_rating}
                                    </Button>
                                </p>
                            break;
                            case 5: // gravity
                                return <p
                                className="control"
                                >
                                    <Button
                                    renderAs={GravityButton}
                                    >
                                        {board.difficulty_rating}
                                    </Button>
                                </p>
                            break;
                            case 6: // heavenly
                                return <p
                                className="control"
                                >
                                    <Button
                                    renderAs={HeavenlyButton}
                                    >
                                        {board.difficulty_rating}
                                    </Button>
                                </p>
                            break;
                            case 7: // vivid
                                return <p
                                className="control"
                                >
                                    <Button
                                    renderAs={VividButton}
                                    >
                                        {board.difficulty_rating}
                                    </Button>
                                </p>
                            break;
                            default:
                                return null;
                        }
                })}
                    </div>
                </div>
            </div>
        </div>
    )

}

export default TrackCard;
